### ISSUE TITLE
Failed when i try to install

### ISSUE THREAD

**Issue by ySpark3** [berbb/Berb.Common#1]
???

**Comment by ySpark3** [comment]
[compile_log_Berb.Common_6DF4C350.txt](https://github.com/berbb/Berb.Common/files/310537/compile_log_Berb.Common_6DF4C350.txt)
[compile_log_Berb.Common_F2F69983.txt](https://github.com/berbb/Berb.Common/files/310538/compile_log_Berb.Common_F2F69983.txt)

**Comment by berbb** [comment]
Did you not read PortAIO github? I'm not helping people that don't read it.
