### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dankmemer420** [berbb/Berb.Common#3]
I've been testing the L# orbwalker since you ported it. And I've actually seen great improvement since it was released, It doesn't stutter at all with 2.5 attack speed and kites perfectly, i was wondering how long till it hits all of PortAIO champs?

**Comment by berbb** [comment]
Very soon, I just have to catch up on porting updates from the other scripts and I will make an enormous update that should allow you too switch between L#'s Orb/TS and EB's orb/TS.

Sorry for the delay!

**Comment by dankmemer420** [comment]
Sounds good man, i've been testing everyday since you released and it's perfect. Good job <3

**Comment by lgndz** [comment]
Does it not integrate with every champ already? Ive been had it selected

**Comment by berbb** [comment]
It works with every champion yes but there's some champions like Vayne in PortAIO that are coded to only work with EB's Orbwalker so champs like her need to be "patched" with L# orb.

**Comment by dankmemer420** [comment]
Can't wait for the Vayne update in the orbwalker.

**Comment by dankmemer420** [comment]
Hey i don't know if porting the challenger series vayne to l# orbwalker did anything with the reset on her Q but its still doing the stutter like with EB.

**Comment by berbb** [comment]
donneeee
