### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by Rhinoz** [berbb/Berb.Common#4]
common is giving me fialed to install, can install other scripts from elobuddy. help

**Comment by berbb** [comment]
update again should be fixed.

**Comment by Rhinoz** [comment]
http://prntscr.com/brd0mc still getting

**Comment by berbb** [comment]
Log?

**Comment by Rhinoz** [comment]
what is log?

**Comment by berbb** [comment]
Nevermind, it's been fixed.
